/**
 * @fileoverview
 * AUTO-GENERATED! DO NOT EDIT!
 * Checked files:
 * * /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/errno.h
 * * /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/errno.h
 */
export enum ErrnoCode {
    ENAME = -1,
    EFUNC = -2,
    ESYNTAX = -3,
    EJAVASCRIPT = -4,
    EPANIC = -255,
    EPERM = 1,
    ENOENT = 2,
    ESRCH = 3,
    EINTR = 4,
    EIO = 5,
    ENXIO = 6,
    ENOEXEC = 8,
    EBADF = 9,
    ECHILD = 10,
    EDEADLK = 11,
    ENOMEM = 12,
    EACCES = 13,
    EFAULT = 14,
    ENOTBLK = 15,
    EBUSY = 16,
    EEXIST = 17,
    EXDEV = 18,
    ENODEV = 19,
    ENOTDIR = 20,
    EISDIR = 21,
    EINVAL = 22,
    ENFILE = 23,
    EMFILE = 24,
    ENOTTY = 25,
    ETXTBSY = 26,
    EFBIG = 27,
    ENOSPC = 28,
    ESPIPE = 29,
    EROFS = 30,
    EMLINK = 31,
    EPIPE = 32,
    EDOM = 33,
    ERANGE = 34,
    EAGAIN = 35,
    EINPROGRESS = 36,
    EALREADY = 37,
    ENOTSOCK = 38,
    EDESTADDRREQ = 39,
    EMSGSIZE = 40,
    EPROTOTYPE = 41,
    ENOPROTOOPT = 42,
    EPROTONOSUPPORT = 43,
    ESOCKTNOSUPPORT = 44,
    ENOTSUP = 45,
    EPFNOSUPPORT = 46,
    EAFNOSUPPORT = 47,
    EADDRINUSE = 48,
    EADDRNOTAVAIL = 49,
    ENETDOWN = 50,
    ENETUNREACH = 51,
    ENETRESET = 52,
    ECONNABORTED = 53,
    ECONNRESET = 54,
    ENOBUFS = 55,
    EISCONN = 56,
    ENOTCONN = 57,
    ESHUTDOWN = 58,
    ETOOMANYREFS = 59,
    ETIMEDOUT = 60,
    ECONNREFUSED = 61,
    ELOOP = 62,
    ENAMETOOLONG = 63,
    EHOSTDOWN = 64,
    EHOSTUNREACH = 65,
    ENOTEMPTY = 66,
    EPROCLIM = 67,
    EUSERS = 68,
    EDQUOT = 69,
    ESTALE = 70,
    EREMOTE = 71,
    EBADRPC = 72,
    ERPCMISMATCH = 73,
    EPROGUNAVAIL = 74,
    EPROGMISMATCH = 75,
    EPROCUNAVAIL = 76,
    ENOLCK = 77,
    ENOSYS = 78,
    EFTYPE = 79,
    EAUTH = 80,
    ENEEDAUTH = 81,
    EPWROFF = 82,
    EDEVERR = 83,
    EOVERFLOW = 84,
    EBADEXEC = 85,
    EBADARCH = 86,
    ESHLIBVERS = 87,
    EBADMACHO = 88,
    ECANCELED = 89,
    EIDRM = 90,
    ENOMSG = 91,
    EILSEQ = 92,
    ENOATTR = 93,
    EBADMSG = 94,
    EMULTIHOP = 95,
    ENODATA = 96,
    ENOLINK = 97,
    ENOSR = 98,
    ENOSTR = 99,
    EPROTO = 100,
    ETIME = 101,
    EOPNOTSUPP = 102,
    ENOPOLICY = 103,
    ENOTRECOVERABLE = 104,
    EOWNERDEAD = 105,
    EQFULL = 106,
    ENOTCAPABLE = 107,
};

export const ErrnoDesc: Record<ErrnoCode, string> = {
    [ErrnoCode.ENAME]: 'Variable not found',
    [ErrnoCode.EFUNC]: 'Function not found',
    [ErrnoCode.ESYNTAX]: 'Unrecognized syntax',
    [ErrnoCode.EJAVASCRIPT]: 'Javascript error',
    [ErrnoCode.EPANIC]: 'Internal error',
    [ErrnoCode.EPERM]: 'Operation not permitted',
    [ErrnoCode.ENOENT]: 'No such file or directory',
    [ErrnoCode.ESRCH]: 'No such process',
    [ErrnoCode.EINTR]: 'Interrupted system call',
    [ErrnoCode.EIO]: 'Input/output error',
    [ErrnoCode.ENXIO]: 'Device not configured',
    [ErrnoCode.ENOEXEC]: 'Exec format error',
    [ErrnoCode.EBADF]: 'Bad file descriptor',
    [ErrnoCode.ECHILD]: 'No child processes',
    [ErrnoCode.EDEADLK]: 'Resource deadlock avoided',
    [ErrnoCode.ENOMEM]: 'Cannot allocate memory',
    [ErrnoCode.EACCES]: 'Permission denied',
    [ErrnoCode.EFAULT]: 'Bad address',
    [ErrnoCode.ENOTBLK]: 'Block device required',
    [ErrnoCode.EBUSY]: 'Device / Resource busy',
    [ErrnoCode.EEXIST]: 'File exists',
    [ErrnoCode.EXDEV]: 'Cross-device link',
    [ErrnoCode.ENODEV]: 'Operation not supported by device',
    [ErrnoCode.ENOTDIR]: 'Not a directory',
    [ErrnoCode.EISDIR]: 'Is a directory',
    [ErrnoCode.EINVAL]: 'Invalid argument',
    [ErrnoCode.ENFILE]: 'Too many open files in system',
    [ErrnoCode.EMFILE]: 'Too many open files',
    [ErrnoCode.ENOTTY]: 'Inappropriate ioctl for device',
    [ErrnoCode.ETXTBSY]: 'Text file busy',
    [ErrnoCode.EFBIG]: 'File too large',
    [ErrnoCode.ENOSPC]: 'No space left on device',
    [ErrnoCode.ESPIPE]: 'Illegal seek',
    [ErrnoCode.EROFS]: 'Read-only file system',
    [ErrnoCode.EMLINK]: 'Too many links',
    [ErrnoCode.EPIPE]: 'Broken pipe',
    [ErrnoCode.EDOM]: 'Numerical argument out of domain',
    [ErrnoCode.ERANGE]: 'Result too large',
    [ErrnoCode.EAGAIN]: 'Resource temporarily unavailable',
    [ErrnoCode.EINPROGRESS]: 'Operation now in progress',
    [ErrnoCode.EALREADY]: 'Operation already in progress',
    [ErrnoCode.ENOTSOCK]: 'Socket operation on non-socket',
    [ErrnoCode.EDESTADDRREQ]: 'Destination address required',
    [ErrnoCode.EMSGSIZE]: 'Message too long',
    [ErrnoCode.EPROTOTYPE]: 'Protocol wrong type for socket',
    [ErrnoCode.ENOPROTOOPT]: 'Protocol not available',
    [ErrnoCode.EPROTONOSUPPORT]: 'Protocol not supported',
    [ErrnoCode.ESOCKTNOSUPPORT]: 'Socket type not supported',
    [ErrnoCode.ENOTSUP]: 'Operation not supported',
    [ErrnoCode.EPFNOSUPPORT]: 'Protocol family not supported',
    [ErrnoCode.EAFNOSUPPORT]: 'Address family not supported by protocol family',
    [ErrnoCode.EADDRINUSE]: 'Address already in use',
    [ErrnoCode.EADDRNOTAVAIL]: "Can't assign requested address",
    [ErrnoCode.ENETDOWN]: 'Network is down',
    [ErrnoCode.ENETUNREACH]: 'Network is unreachable',
    [ErrnoCode.ENETRESET]: 'Network dropped connection on reset',
    [ErrnoCode.ECONNABORTED]: 'Software caused connection abort',
    [ErrnoCode.ECONNRESET]: 'Connection reset by peer',
    [ErrnoCode.ENOBUFS]: 'No buffer space available',
    [ErrnoCode.EISCONN]: 'Socket is already connected',
    [ErrnoCode.ENOTCONN]: 'Socket is not connected',
    [ErrnoCode.ESHUTDOWN]: "Can't send after socket shutdown",
    [ErrnoCode.ETOOMANYREFS]: "Too many references: can't splice",
    [ErrnoCode.ETIMEDOUT]: 'Operation timed out',
    [ErrnoCode.ECONNREFUSED]: 'Connection refused',
    [ErrnoCode.ELOOP]: 'Too many levels of symbolic links',
    [ErrnoCode.ENAMETOOLONG]: 'File name too long',
    [ErrnoCode.EHOSTDOWN]: 'Host is down',
    [ErrnoCode.EHOSTUNREACH]: 'No route to host',
    [ErrnoCode.ENOTEMPTY]: 'Directory not empty',
    [ErrnoCode.EPROCLIM]: 'Too many processes',
    [ErrnoCode.EUSERS]: 'Too many users',
    [ErrnoCode.EDQUOT]: 'Disc quota exceeded',
    [ErrnoCode.ESTALE]: 'Stale NFS file handle',
    [ErrnoCode.EREMOTE]: 'Too many levels of remote in path',
    [ErrnoCode.EBADRPC]: 'RPC struct is bad',
    [ErrnoCode.ERPCMISMATCH]: 'RPC version wrong',
    [ErrnoCode.EPROGUNAVAIL]: 'RPC prog. not avail',
    [ErrnoCode.EPROGMISMATCH]: 'Program version wrong',
    [ErrnoCode.EPROCUNAVAIL]: 'Bad procedure for program',
    [ErrnoCode.ENOLCK]: 'No locks available',
    [ErrnoCode.ENOSYS]: 'Function not implemented',
    [ErrnoCode.EFTYPE]: 'Inappropriate file type or format',
    [ErrnoCode.EAUTH]: 'Authentication error',
    [ErrnoCode.ENEEDAUTH]: 'Need authenticator',
    [ErrnoCode.EPWROFF]: 'Device power is off',
    [ErrnoCode.EDEVERR]: 'Device error, e.g. paper out',
    [ErrnoCode.EOVERFLOW]: 'Value too large to be stored in data type',
    [ErrnoCode.EBADEXEC]: 'Bad executable',
    [ErrnoCode.EBADARCH]: 'Bad CPU type in executable',
    [ErrnoCode.ESHLIBVERS]: 'Shared library version mismatch',
    [ErrnoCode.EBADMACHO]: 'Malformed Macho file',
    [ErrnoCode.ECANCELED]: 'Operation canceled',
    [ErrnoCode.EIDRM]: 'Identifier removed',
    [ErrnoCode.ENOMSG]: 'No message of desired type',
    [ErrnoCode.EILSEQ]: 'Illegal byte sequence',
    [ErrnoCode.ENOATTR]: 'Attribute not found',
    [ErrnoCode.EBADMSG]: 'Bad message',
    [ErrnoCode.EMULTIHOP]: 'Reserved',
    [ErrnoCode.ENODATA]: 'No message available on STREAM',
    [ErrnoCode.ENOLINK]: 'Reserved',
    [ErrnoCode.ENOSR]: 'No STREAM resources',
    [ErrnoCode.ENOSTR]: 'Not a STREAM',
    [ErrnoCode.EPROTO]: 'Protocol error',
    [ErrnoCode.ETIME]: 'STREAM ioctl timeout',
    [ErrnoCode.EOPNOTSUPP]: 'Operation not supported on socket',
    [ErrnoCode.ENOPOLICY]: 'No such policy registered',
    [ErrnoCode.ENOTRECOVERABLE]: 'State not recoverable',
    [ErrnoCode.EOWNERDEAD]: 'Previous owner died',
    [ErrnoCode.EQFULL]: 'Interface output queue is full',
    [ErrnoCode.ENOTCAPABLE]: 'Capabilities insufficient',
};
